// Generated by CoffeeScript 2.6.1
var config, md5, mkUsrDir;

config = require("../../config/config");

mkUsrDir = require("../tools/tool_mkUsrDir");

md5 = config.md5;

module.exports = {
  method: "post",
  path: "/dzLogin",
  options: {
    auth: false
  },
  handler: async function(req, h) {
    var db, err, loginUser, que, setSession, user, userExt;
    try {
      db = req.server.db;
      que = req.payload;
      console.log(que.user);
      userExt = (await db.icat_users_extend.findOne({
        where: {
          user: que.user
        }
      }));
      if (!userExt) {
        return {
          ok: false,
          msg: "用户不存在"
        };
      }
      user = (await db.icat_users.findOne({
        include: db.icat_users_extend,
        where: {
          user: userExt.user,
          password: md5(md5(md5((md5(que.password)) + userExt.salt)) + config.key)
        }
      }));
      if (user) {
        // 登录成功，写入cookie
        setSession = async function() {
          return (await req.cookieAuth.set({
            uid: user.uid,
            user: user.user
          }));
        };
        await setSession();
        //更新最后登录时间
        loginUser = (await db.icat_users_extend.findOne({
          where: {
            uid: user.uid
          }
        }));
        loginUser.loginTimestamp = Date.now();
        await loginUser.save();
        return {
          ok: true,
          msg: "登录成功",
          data: user.icat_users_extend
        };
      } else {
        return {
          ok: false,
          msg: "用户名或密码错误"
        };
      }
    } catch (error) {
      err = error;
      console.log(e);
      return {
        ok: false,
        valid: false,
        msg: "服务器内部错误"
      };
    }
  }
};
