// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/logout",
  handler: async function(req, h) {
    await req.cookieAuth.clear();
    return {
      ok: true,
      msg: "登出成功"
    };
  }
};
