// Generated by CoffeeScript 2.6.1
var createAPI;

createAPI = require("../../tools/api/createAPI");

module.exports = createAPI("user", {
  tableName: "icat_users_extend",
  idName: "uid",
  cnName: "用户",
  delPower: 100,
  delBeforeDeleteData: async function(sendParams) {
    var auth, config, db, h, par, que, req, t, user, userName;
    ({req, h, db, que, par, auth, config, t} = sendParams);
    user = (await db.icat_users.findOne({
      where: {
        uid: Number(par.uid)
      },
      transaction: t
    }));
    userName = user.user;
    if (!user) {
      await t.commit();
      return sendParams.stop = {
        ok: false,
        msg: "用户不存在"
      };
    }
    await user.destroy({
      transaction: t
    });
    await t.commit();
    return sendParams.stop = {
      ok: true,
      msg: `用户：${userName}，uid：${par.uid}，已删除`
    };
  }
}).del;
