// Generated by CoffeeScript 2.6.1
module.exports = {
  path: "/api/users/addGood/{uid?}",
  method: "post",
  options: {
    validate: {
      params: Joi.object({
        uid: Joi.string().pattern(/^\d+$/)
      }),
      payload: Joi.object({
        goodid: Joi.number().min(1),
        count: Joi.number().min(1)
      })
    }
  },
  handler: async function(req, h) {
    var auth, db, err, good, goodRelation, i, par, que, ref, t, times, user, value2;
    try {
      db = req.server.db;
      que = req.payload;
      par = req.params;
      auth = req.auth.credentials;
      t = (await db.mysql.transaction());
      if (auth.icat_users_extend.power < 90) {
        await t.rollback();
        return {
          ok: false,
          msg: "权限不足"
        };
      }
      user = (await db.icat_users_extend.findOne({
        attributes: ["uid"],
        where: {
          uid: Number(par.uid)
        },
        transaction: t
      }));
      if (!user) {
        await t.rollback();
        return {
          ok: false,
          msg: "用户不存在"
        };
      }
      good = (await db.icat_goods.findOne({
        attributes: ["goodid"],
        where: {
          goodid: que.goodid
        },
        transaction: t
      }));
      //检查是否有该物品
      goodRelation = (await db.icat_relations.findOne({
        attributes: ["relationid", "icatGoodGoodid", "icatUsersExtendUextid", "value", "value2"],
        where: {
          icatGoodGoodid: good.goodid,
          icatUsersExtendUextid: auth.uid
        },
        transaction: t
      }));
      if (goodRelation) {
        /*     
           await goodRelation.increment
             value:que.count
           ,
             transaction:t
           */
        goodRelation.value = Number(goodRelation.value) + Number(que.count);
        if (goodRelation.value2) {
          value2 = JSON.parse(goodRelation.value2);
          for (times = i = 0, ref = que.count; (0 <= ref ? i < ref : i > ref); times = 0 <= ref ? ++i : --i) {
            value2.push(Date.now());
          }
          goodRelation.value2 = JSON.stringify(value2);
        } else {
          goodRelation.value2 = JSON.stringify([Date.now()]);
        }
        await goodRelation.save({
          transaction: t
        });
      } else {
        await auth.icat_users_extend.addIcat_goods(good, {
          through: {
            whoUse: "users_goods",
            name: "个数",
            key: "count",
            type: "number",
            value: que.count,
            name2: "获取时间组",
            key2: "getTimes",
            type2: "array",
            value2: JSON.stringify([Date.now()])
          },
          transaction: t
        });
      }
      await t.commit();
      return {
        ok: true,
        msg: "物品发放成功"
      };
    } catch (error) {
      err = error;
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
