// Generated by CoffeeScript 2.6.1
var createAPI;

createAPI = require("../../tools/api/createAPI");

module.exports = createAPI("user", {
  tableName: "icat_users_extend",
  idName: "uid",
  cnName: "用户",
  setPower: 90,
  setPayload: {
    power: Joi.number().strict().allow(null),
    name: Joi.string().allow(null),
    avatar: Joi.string().allow(null),
    sex: Joi.number().allow(null),
    age: Joi.number().allow(null),
    introduction: Joi.string().allow(null),
    qq: Joi.number().allow(null),
    wechat: Joi.string().allow(null),
    email: Joi.string().email().allow(null),
    emailVerify: Joi.number().valid(0, 1).allow(null),
    loginTimestamp: Joi.number().allow(null),
    signTimestamp: Joi.number().allow(null)
  },
  setFields: ["power", "name", "avatar", "sex", "age", "brithday", "introduction", "qq", "wechat", "email", "emailVerify", "loginTimestamp", "signTimestamp"]
}).set;
