// Generated by CoffeeScript 2.6.1
module.exports = async function(db) {
  /*

  await gn00.addIcat_credit credit,
    through:
      whoUse:"goods_credits"
      name:"价格"
      key:"price"
      type:"number"
      value:"800"
  */
  /*
  await ticket.addIcat_credit credit,
    through:
      whoUse:"goods_credits"
      name:"价格"
      key:"price"
      type:"number"
      value:"1000"
  */
  var Aaron, christmasHat, credit, gn00, goodName, i, len, ref, results, ticket;
  credit = (await db.icat_credits.findOne({
    where: {
      name: "喵点"
    }
  }));
  christmasHat = ((await db.icat_goods.findOrCreate({
    where: {
      name: "圣诞帽"
    },
    defaults: {
      name: "圣诞帽",
      description: "圣诞节活动获取",
      consumable: 0,
      icon: "/statics/good/christmasHat.svg",
      purchaseLimit: -1,
      storage: 100
    }
  })))[0];
  //圣诞帽价格
  /*
  await christmasHat.addIcat_credit credit,
    through:
      whoUse:"goods_credits"
      name:"价格"
      key:"price"
      type:"number"
      value:"200"
  */
  ticket = ((await db.icat_goods.findOrCreate({
    where: {
      name: "1000积分兑换券"
    },
    defaults: {
      name: "1000积分兑换券",
      description: "2022年元旦活动获取",
      consumable: 1,
      icon: "/statics/good/ticket.svg",
      purchaseLimit: -1,
      storage: 100
    }
  })))[0];
  gn00 = ((await db.icat_goods.findOrCreate({
    where: {
      name: "存档网络通行券"
    },
    defaults: {
      name: "存档网络通行券",
      description: "技术宅存档网络积分兑换券,含1000点宅币",
      consumable: 1,
      icon: "/statics/good/ticket.svg",
      purchaseLimit: -1,
      storage: 100
    }
  })))[0];
  Aaron = ((await db.icat_goods.findOrCreate({
    where: {
      name: "艾伦"
    },
    defaults: {
      name: "艾伦",
      description: "红头发的剑士",
      consumable: 1,
      icon: "/statics/good/aaron.jpg",
      purchaseLimit: -1,
      storage: 100
    }
  })))[0];
  ref = ["带刀侍卫怀疑的目光", "带刀侍卫可怜的眼神", "带刀侍卫鄙夷的一瞥", "带刀侍卫赞许的认可", "带刀侍卫同款刀鞘", "刀侍卫的佩刀"];
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    goodName = ref[i];
    results.push(((await db.icat_goods.findOrCreate({
      where: {
        name: goodName
      },
      defaults: {
        name: goodName,
        type: "任务道具",
        description: goodName,
        consumable: 1,
        icon: "/statics/good/taskItem.jpg",
        purchaseLimit: -1,
        storage: 100
      }
    })))[0]);
  }
  return results;
};
