// Generated by CoffeeScript 2.6.1
module.exports = function(db) {
  var groups, i, item, len, results;
  groups = [
    {
      name: "管理员",
      type: "管理组"
    },
    {
      name: "版主",
      type: "管理组"
    },
    {
      name: "总版主",
      type: "管理组"
    },
    {
      name: "会员",
      type: "内置组"
    },
    {
      name: "游客",
      type: "内置组"
    },
    {
      name: "禁止发言",
      type: "内置组"
    },
    {
      name: "待验证会员",
      type: "内置组"
    },
    {
      name: "vip",
      type: "特殊组"
    },
    {
      name: "svip",
      type: "特殊组"
    },
    {
      name: "萌新",
      type: "会员组",
      points: "10" //这里指经验值Exp 而不是经验值计算后的等级
    },
    {
      name: "序章",
      type: "会员组",
      points: "100"
    },
    {
      name: "第一章",
      type: "会员组",
      points: "300"
    },
    {
      name: "第二章",
      type: "会员组",
      points: "500"
    },
    {
      name: "第三章",
      type: "会员组",
      points: "1000"
    },
    {
      name: "第四章",
      type: "会员组",
      points: "3000"
    },
    {
      name: "第五章",
      type: "会员组",
      points: "5000"
    },
    {
      name: "第六章",
      type: "会员组",
      points: "8000"
    },
    {
      name: "最终章",
      type: "会员组",
      points: "10000"
    }
  ];
  results = [];
  for (i = 0, len = groups.length; i < len; i++) {
    item = groups[i];
    results.push((async function(item) {
      return (await db.icat_groups.findOrCreate({
        where: {
          name: item.name
        },
        defaults: {
          name: item.name,
          type: item.type
        }
      }));
    })(item));
  }
  return results;
};
