// Generated by CoffeeScript 2.6.1
/*
空值请使用汉字”空“注明
因为字段设置不允许空
*/
var crypto, md5;

crypto = require("crypto");

md5 = function(value) {
  return crypto.createHash("md5").update(value).digest("hex");
};

module.exports = async function(db) {
  var err;
  try {
    //创建初始用户
    //注意：因为作用域允许，直接通过变量访问表而没有使用参数
    await db.icat_users.findOrCreate({
      where: {
        uid: 1
      },
      defaults: {
        user: "admin",
        password: "admin"
      }
    });
    await db.icat_users_extend.findOrCreate({
      where: {
        uid: 1
      },
      defaults: {
        user: "admin",
        group: "admin",
        power: 100,
        signTimestamp: Date.now(),
        loginTimestamp: Date.now()
      }
    });
    //初始化其余项目
    await require("./db_init_createOptions")(db);
    await require("./db_init_createPowers")(db);
    await require("./db_init_createGroups")(db);
    //await require("./db_init_createBlocks")()
    await require("./db_init_createCredits")(db);
    await require("./db_init_createGoods")(db);
  } catch (error) {
    err = error;
    return console.log(err);
  }
};
