// Generated by CoffeeScript 2.6.1
module.exports = async function(db) {
  var blocks, i, index, item, len, results;
  blocks = [
    {
      name: "新喵报到",
      sizeType: 3,
      icon: "./statics/block/新宅.png"
    },
    {
      name: "水世界",
      sizeType: 2,
      icon: "./statics/block/水区.png"
    },
    {
      name: "活动中心",
      sizeType: 1,
      icon: "./statics/block/活动.png"
    },
    {
      name: "日记手账",
      sizeType: 1,
      icon: "./statics/block/日记.png"
    },
    {
      name: "卖萌花园",
      sizeType: 3,
      icon: "./statics/block/卖萌花园.png"
    },
    {
      name: "影视厅",
      sizeType: 3,
      icon: "./statics/block/电影.png"
    },
    {
      name: "摄影棚",
      sizeType: 1,
      icon: "./statics/block/摄影.png"
    },
    {
      name: "侦探所",
      sizeType: 1,
      icon: "./statics/block/侦探事务所.png"
    }
  ];
  results = [];
  for (index = i = 0, len = blocks.length; i < len; index = ++i) {
    item = blocks[index];
    item.order = index;
    results.push((await db.icat_posts.findOrCreate({
      where: {
        content: JSON.stringify(item)
      },
      defaults: {
        uid: 1,
        author: "系统",
        title: `{{{block}}}-${item.name}`,
        content: JSON.stringify(item),
        contentType: "block",
        createTime: new Date().getTime(),
        finallyTime: new Date().getTime(),
        linkid: 0,
        linkChain: 0
      }
    })));
  }
  return results;
};
