// Generated by CoffeeScript 2.6.1
module.exports = async function(db) {
  var credit, credits, i, len, results;
  credits = [
    {
      name: "喵点",
      unit: "点",
      rate: 100,
      isUse: 1,
      allowScore: 1
    },
    {
      name: "活跃",
      unit: "点",
      rate: 0,
      isUse: 1
    },
    {
      name: "经验",
      unit: "点",
      rate: 0,
      isUse: 1
    },
    {
      name: "玉韘",
      unit: "枚",
      rate: 1,
      isUse: 1
    },
    {
      name: "生命",
      unit: "点",
      rate: 0,
      isUse: 1
    },
    {
      name: "法力",
      unit: "%",
      rate: 0,
      isUse: 1
    },
    {
      name: "攻击",
      unit: "点",
      rate: 0,
      isUse: 1
    },
    {
      name: "法术",
      unit: "点",
      rate: 0,
      isUse: 1
    },
    {
      name: "物防",
      unit: "点",
      rate: 0,
      isUse: 1
    },
    {
      name: "法防",
      unit: "点",
      rate: 0,
      isUse: 1
    },
    {
      name: "物穿",
      unit: "%",
      rate: 0,
      isUse: 1
    },
    {
      name: "法穿",
      unit: "%",
      rate: 0,
      isUse: 1
    },
    {
      name: "攻速",
      unit: "%",
      rate: 0,
      isUse: 1
    },
    {
      name: "移速",
      unit: "%",
      rate: 0,
      isUse: 1
    },
    {
      name: "闪避",
      unit: "%",
      rate: 0,
      isUse: 1
    },
    {
      name: "暴击",
      unit: "%",
      rate: 0,
      isUse: 1
    },
    {
      name: "暴伤",
      unit: "%",
      rate: 0,
      isUse: 1
    },
    {
      name: "冷减",
      unit: "%",
      rate: 0,
      isUse: 1
    },
    {
      name: "世界",
      unit: "",
      rate: 0,
      isUse: 1
    }
  ];
  results = [];
  for (i = 0, len = credits.length; i < len; i++) {
    credit = credits[i];
    results.push((await db.icat_credits.findOrCreate({
      defaults: credit,
      where: {
        name: credit.name
      }
    })));
  }
  return results;
};
