// Generated by CoffeeScript 2.6.1
var fs, moment, p, pathLib, process, root, t, t1, t2, t3;

fs = require("fs-extra");

pathLib = require("path");

p = console.log;

process = require("child_process");

moment = require("moment");

t = new Date();

t1 = t.getTime();

t2 = t.getTimezoneOffset() * 60 * 1000;

t3 = t1 - t2;

t = new Date(t3);

root = pathLib.resolve("./");

console.log(root);

(function() {
  var err, excludeFiles;
  excludeFiles = [
    "install/front/src/",
    "install/installed.json",
    "databases/tables/icat_websites.js", //空白项目用
    "apis/websites/", //空白项目用
    "apis/invite/", //空白项目用
    "certs/", //空白项目用
    "attachment/",
    "upload/",
    "node_modules",
    "render.zip",
    "node_modules.zip",
    ".git",
    ".gitignore",
    ".vscode",
    "www/data/",
    "www/src",
    "iconDesign/",
    "www/public/statics/block/",
    "www/public/statics/green/tileset/indoor.png", //素材
    "www/public/statics/green/tileset/outdoor.png",
    "www/public/statics/green/tileset/wall.png",
    "apis/robot/records.json",
    "apis/invite/invites.txt",
    "config/config.js",
    "www/dist/index.html",
    "www/dist/icat.html",
    "www/dist/statics/block/",
    "*.coffee"
  ].map((item) => {
    if (item.match(/^\*/g)) {
      return `--exclude=${item}`;
    } else {
      return `--exclude=^${item}$`;
    }
  }).join(" ");
  console.log(excludeFiles);
  try {
    //await fs.ensureDir "#{root}/upload/tmp"
    return process.exec(`tar -zcf ./upload/icat_lite_public_${moment(t).format("YYYY年MM月DD日_HH时mm分ss秒")}.tar.gz ${excludeFiles} .`, function(err, stdout, stderr) {
      if (err) {
        p(err);
      }
      if (stdout) {
        p(stdout);
      }
      if (stderr) {
        return p(stderr);
      }
    });
  } catch (error) {
    err = error;
    return console.log(err);
  }
})();
