// Generated by CoffeeScript 2.6.1
var installData;

installData = require("../../install_data");

module.exports = (server) => {
  return server.route({
    method: "post",
    path: "/stop",
    handler: function(req, h) {
      var err;
      try {
        console.log("启动中");
        installData.miao.kill();
        console.log("服务停止命令已下达");
        return {
          ok: true,
          msg: "服务停止命令已下达"
        };
      } catch (error) {
        //return h.redirect "/"
        err = error;
        console.log(err);
        return {
          ok: false,
          msg: "服务器内部错误"
        };
      }
    }
  });
};
