// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/api/credits/get/{uid?}",
  options: {
    auth: false,
    validate: {
      params: Joi.object({
        uid: Joi.string().pattern(/^\d+$/)
      })
    }
  },
  handler: async function(req, h) {
    var auth, credit, credits, creditsInfo, db, err, i, len, que;
    try {
      db = req.server.db;
      que = req.query;
      auth = req.auth.credentials;
      // 注意参数类型为字符串
      credits = (await db.icat_credits.findAll({
        where: {
          isUse: true
        }
      }));
      creditsInfo = void 0;
      if (req.params.uid != null) {
        if (typeof Number(req.params.uid) === "number") { //如果uid不是NaN或零（uid从1开始）
          creditsInfo = [];
          for (i = 0, len = credits.length; i < len; i++) {
            credit = credits[i];
            creditsInfo.push({
              name: credit.name,
              value: ((await db.icat_credits_calc.sum("calc", {
                where: {
                  uid: req.params.uid,
                  creditName: credit.name
                }
              }))) || 0
            });
          }
          return {
            ok: true,
            msg: "获取用户积分成功",
            data: creditsInfo //NaN或零
          };
        } else {
          return {
            ok: false,
            msg: "uid异常，查询积分列表请留空"
          };
        }
      } else {
        return {
          ok: true,
          msg: "获取积分列表成功",
          data: credits
        }; //如果uid存在
      }
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
