// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/api/admin/groups/get",
  handler: async function(req, h) {
    var auth, data, db, err, que;
    que = req.query;
    db = req.server.db;
    auth = req.auth.credentials;
    try {
      if (auth.icat_users_extend.power >= 90) {
        data = (await db.icat_groups.findAll());
        return {
          ok: true,
          msg: "获取用户组成功",
          data: data
        };
      } else {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
