// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "delete",
  path: "/api/admin/groups/del/{gid}",
  handler: async function(req, h) {
    var auth, db, err, gid, que;
    que = req.query;
    db = req.server.db;
    auth = req.auth.credentials;
    try {
      if (auth.icat_users_extend.power >= 90) {
        gid = Number(req.params.gid);
        await db.icat_groups.destory({
          where: {
            gid: gid
          }
        });
        return {
          ok: true,
          msg: "用户组删除成功"
        };
      } else {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
