// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/api/admin/options/get",
  handler: async function(req, h) {
    var auth, db, err, options, que;
    que = req.query;
    db = req.server.db;
    auth = req.auth.credentials;
    try {
      if (auth.icat_users_extend.power >= 90) {
        options = (await db.icat_options.findAll());
        return {
          ok: true,
          msg: "控制台选项读取成功",
          data: options
        };
      } else {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
