// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "post",
  path: "/api/admin/groups/set/{gid?}",
  handler: async function(req, h) {
    var auth, db, err, gid, que, regs;
    que = req.payload;
    db = req.server.db;
    auth = req.auth.credentials;
    try {
      if (auth.icat_users_extend.power >= 90) {
        gid = Number(req.params.gid);
        regs = [
          /^.{0,20}$/, //name
          /^\w{0,20}$/, //color
          /^\d{0,3}$/, //level
          /^\w{0,5}$/, //type
          /^\w{0,100}$/, //icon
          /^\d{0,10}$/, //points
          /^\d{0,10}$/, //fee
          /^\w{0,20}$/ //feePointType
        ];
        if (Object.keys(que).every((key) => {
          return regs.every((reg) => {
            return reg.test(que[key]);
          });
        })) {
          return {
            ok: false,
            msg: "请检查字段类型和范围"
          };
        }
        if (!["管理组", "内置组", "会员组", "特殊组"].find((item) => {
          return item === gid.type;
        })) {
          return {
            ok: false,
            msg: "非预期的type"
          };
        }
        if (gid != null) {
          await db.icat_groups.update({...que}, {
            where: {
              gid: gid
            }
          });
        } else {
          await db.icat_groups.create({...que});
        }
        return {
          ok: true,
          msg: "资源已更新或创建"
        };
      } else {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "写入异常，请检查字段"
      };
    }
  }
};
