// Generated by CoffeeScript 2.6.1
var Iron, fs, installData, pathLib;

fs = require("fs-extra");

installData = require("../../install_data");

Iron = require("@hapi/iron");

pathLib = require("path");

module.exports = (server) => {
  return server.route({
    method: "get",
    path: "/info",
    handler: function(req, h) {
      var err, ref, ref1, ref2, ref3, ref4, ref5, ret;
      try {
        ret = {
          ok: true,
          data: {
            miao: {
              logs: ((ref = installData.miao) != null ? ref.logs : void 0) || [],
              status: !installData.miao || !installData.miao.process || ((ref1 = installData.miao.process) != null ? ref1.killed : void 0) ? "stop" : "start"
            },
            database: {
              logs: ((ref2 = installData.database) != null ? ref2.logs : void 0) || [],
              status: !installData.database || !installData.database.process || ((ref3 = installData.database.process) != null ? ref3.killed : void 0) ? "stop" : "start"
            },
            command: {
              logs: ((ref4 = installData.command) != null ? ref4.logs : void 0) || [],
              status: !installData.command || !installData.command.process || ((ref5 = installData.command.process) != null ? ref5.killed : void 0) ? "stop" : "start"
            }
          },
          msg: "信息获取成功"
        };
        return ret;
      } catch (error) {
        err = error;
        console.log(err);
        return {
          ok: false,
          msg: "服务器内部错误"
        };
      }
    }
  });
};
