// Generated by CoffeeScript 2.6.1
var fs, pathLib;

fs = require("fs-extra");

pathLib = require("path");

module.exports = (server) => {
  return server.route({
    method: "post",
    path: "/del",
    handler: async function(req, h) {
      var err, file;
      try {
        file = (await (async function() {
          try {
            return (await fs.stat(pathLib.resolve("./installed.json")));
          } catch (error) {
            return false;
          }
        })());
        if (file) {
          await fs.remove(pathLib.resolve("./installed.json"));
          return {
            ok: true,
            msg: "删除配置成功"
          };
        } else {
          return {
            ok: false,
            msg: "配置文件不存在"
          };
        }
      } catch (error) {
        err = error;
        console.log(err);
        return {
          ok: false,
          msg: "服务器内部错误"
        };
      }
    }
  });
};
