// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    ipsid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    ip: {
      type: DataTypes.STRING,
      allowNull: false
    },
    timestamp: {
      type: DataTypes.BIGINT,
      allowNull: false
    },
    headers: {
      type: DataTypes.JSON,
      allowNull: false
    },
    count: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    coolDown: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 10
    }
  };
  return mysql.define("icat_cache_ips", data, {
    freezeTableName: true,
    indexs: [
      {
        unique: true,
        fields: ["ip"]
      },
      {
        fields: ["timestamp"]
      }
    ]
  });
};
