// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    que: {
      type: DataTypes.JSON,
      allowNull: false
    },
    par: {
      type: DataTypes.JSON,
      allowNull: false
    },
    content: {
      type: DataTypes.JSON,
      allowNull: false
    },
    timestamp: {
      type: DataTypes.BIGINT,
      allowNull: false
    }
  };
  return mysql.define("icat_cache_linkids", data, {
    freezeTableName: true,
    indexs: [
      {
        unique: true,
        fields: ["que",
      "par"]
      }
    ]
  });
};
