// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/api/notices/news/get/{msgType?}",
  options: {
    validate: {
      params: Joi.object({
        msgType: Joi.string()
      })
    }
  },
  handler: async function(req, h) {
    var auth, data, db, err, que;
    que = req.query;
    db = req.server.db;
    auth = req.auth.credentials;
    try {
      req.params.msgType;
      data = (await db.icat_notices.count({
        where: {
          ...(req.params.msgType ? {
            msgType: req.params.msgType
          } : void 0),
          receiverId: auth.uid,
          readTime: null
        }
      }));
      return {
        ok: true,
        msg: "获取未读消息数成功",
        data: data
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        valid: false,
        msg: "服务器内部错误"
      };
    }
  }
};
