// Generated by CoffeeScript 2.6.1
var DataTypes, Sequelize, config, fsp, pathLib;

({Sequelize, DataTypes} = require('sequelize'));

config = require("../config/config");

pathLib = require("path");

fsp = (require("fs")).promises;

module.exports = new Sequelize({
  host: config.db.host,
  database: config.db.database,
  username: config.db.user,
  password: config.db.password,
  port: config.db.port,
  dialect: config.db.dialect,
  connectionLimit: config.db.connectionLimit,
  logging: function(msg) {
    var err;
    try {

    } catch (error) {
      //console.log msg
      //await fsp.appendFile pathLib.resolve("./database/db_log.sql"),(msg+"\n"+"======="+"\n")
      err = error;
      return console.log(err);
    }
  }
});
