// Generated by CoffeeScript 2.6.1
var DataTypes, Sequelize, config, fsp, pathLib;

({Sequelize, DataTypes} = require('sequelize'));

config = require("../config/config");

pathLib = require("path");

fsp = (require("fs")).promises;

module.exports = new Sequelize({
  database: "sqlite::memory",
  dialect: "sqlite",
  logging: function(msg) {
    var err;
    try {

    } catch (error) {
      //console.log msg
      //await fsp.appendFile pathLib.resolve("./database/db_log.sql"),(msg+"\n"+"======="+"\n")
      err = error;
      return console.log(err);
    }
  }
});
