// Generated by CoffeeScript 2.6.1
module.exports = {
  method: 'get',
  path: "/statics/{param*}",
  handler: {
    directory: {
      path: 'public/statics'
    }
  },
  options: {
    auth: false
  }
};
