// Generated by CoffeeScript 2.6.1
var index;

index = require("./index");

module.exports = {
  path: "/lite", //pid linkid limit offset count
  method: "get",
  options: {
    auth: false
  },
  handler: index.bind(this)
};
