// Generated by CoffeeScript 2.6.1
//index = require "./index"
module.exports = {
  path: "/", //pid linkid limit offset count
  method: "get",
  options: {
    auth: false
  },
  //handler: index.bind @
  handler: async function(req, h) {
    var err, html, ref;
    try {
      html = (await req.server.inject({
        //url:"/post_list/-1_0_0_0.html"
        url: "/lite"
      }));
      return html.result;
      if (((ref = req.headers) != null ? ref["x-forwarded-host"] : void 0) && (req.headers["x-forwarded-host"] === "icat.gn00.com" || req.headers["x-forwarded-host"][0] === "icat.gn00.com")) {
        return h.redirect("https://www.gn00.com/forum.php");
      } else {
        return html.result;
      }
    } catch (error) {
      err = error;
      return console.log(err);
    }
  }
};
