// Generated by CoffeeScript 2.6.1
var index;

index = require("./index");

module.exports = {
  path: "/{pid}-{linkid}-{offset}.html", //pid linkid limit offset count
  method: "get",
  options: {
    auth: false,
    validate: {
      params: Joi.object({
        pid: Joi.number().allow("null"),
        linkid: Joi.number().allow("null"),
        offset: Joi.number().allow("null")
      })
    }
  },
  //三个数字分别是pid,linkid,和offset
  handler: index.bind(this)
};
