// Generated by CoffeeScript 2.6.1
module.exports = {
  ips: {},
  checkPass: function(ip) {
    if (ips[ip]) {
      return true;
    } else {
      return false;
    }
  },
  addIp: function(ip) {
    return ips[ip] = true;
  },
  clearIps: function() {
    return this.ips = {};
  },
  checkData: function(xyArr) {},
  joinIp: function(ip) {}
};
