// Generated by CoffeeScript 2.6.1
var createAPI;

createAPI = require("../../tools/api/createAPI");

module.exports = createAPI("file", {
  cnName: "附件",
  getBeforeCreateData: function(sendParams) {
    var auth, db, h, par, que, req;
    ({que, par, req, h, db, auth} = sendParams);
    if (!auth) {
      return sendParams.stop = {
        ok: false,
        msg: "非法请求"
      };
    }
    if (!auth.uid && auth.icat_users_extend.power < 90) {
      return sendParams.stop = {
        ok: false,
        msg: "非法请求"
      };
    }
  },
  //只有管理员有权限请求所有附件
  getFindAllWhere: function(sendParams) {
    var auth, db, h, par, que, req;
    ({que, par, req, h, db, auth} = sendParams);
    if (auth.uid) {
      return {
        uid: auth.uid
      };
    } else {
      return {};
    }
  },
  getAllCountWhere: function(sendParams) {
    var auth, db, h, par, que, req;
    ({que, par, req, h, db, auth} = sendParams);
    if (auth.uid) {
      return {
        uid: auth.uid
      };
    } else {
      return {};
    }
  }
}).get;
