// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "post",
  path: "/api/files/unLinkPost/{fileid}",
  options: {
    validate: {
      params: Joi.object({
        fileid: Joi.string().pattern(/^\d+$/)
      }),
      payload: Joi.object({
        pid: Joi.string().pattern(/^\d+$/)
      })
    }
  },
  handler: async function(req, h) {
    var auth, db, err, file, par, que, thread;
    que = req.payload;
    db = req.server.db;
    auth = req.auth.credentials;
    par = req.params;
    try {
      file = (await db.icat_files.findOne({
        where: {
          fileid: Number(par.fileid)
        }
      }));
      thread = (await db.icat_posts.findOne({
        where: {
          pid: Number(que.pid),
          uid: auth.uid
        }
      }));
      await thread.removeIcat_files(file);
      return {
        ok: true,
        msg: "文件已解除与帖子的关联"
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
