// Generated by CoffeeScript 2.6.1
var checkType, db;

checkType = require("icat_checktype");

db = require("../database/db_main");

module.exports = {
  data: null,
  json: null,
  pull: async function() {
    var err;
    try {
      this.json = {};
      this.data = (await db.icat_options.findAll());
      return this.data.forEach((option) => {
        return this.json[option.key] = option;
      });
    } catch (error) {
      err = error;
      throw err;
    }
  },
  set: async function(key, value) {
    var err, option;
    try {
      if (!this.data) {
        await this.pull();
      }
      option = this.data.find((option) => {
        return option.key === key;
      });
      option.key = value;
      await option.save();
      return (await this.pull());
    } catch (error) {
      err = error;
      throw err;
    }
  },
  get: async function(key) {
    var err, option;
    try {
      if (!this.data) {
        await this.pull();
      }
      option = this.json[key];
      if (option) {
        return option.value;
      } else {
        throw new Error(`获取设置${key}失败`);
      }
    } catch (error) {
      err = error;
      throw err;
    }
  }
};
