// Generated by CoffeeScript 2.6.1
var createAPI;

createAPI = require("../../tools/api/createAPI");

module.exports = createAPI("option", {
  cnName: "选项",
  getQuery: {
    key: Joi.string()
  },
  getAfterCreateData: async function(sendParams) {
    var auth, db, que;
    ({db, que, auth} = sendParams);
    if (que.key) {
      sendParams.data = (await db.icat_options.findOne({
        where: {
          key: que.key
        }
      }));
    }
    if ((auth && auth.icat_users_extend.power < 100) || !auth) {
      return sendParams.data = sendParams.data.map((item) => {
        var output;
        output = JSON.parse(JSON.stringify(item));
        //item.key.match "email_password" or item.key is "email_userName"
        if (["email_password", "email_userName", "pay_aliAppid", "pay_qqAppid", "pay_qqMchid", "pay_qqOperatorid", "pay_qqOperatorPassword", "pay_qqAPIkey"].some((name) => {
          return item.key.match(name);
        })) {
          output.value = "";
          delete output.joi;
          return output;
        } else {
          delete output.joi;
          return output;
        }
      });
    }
  }
}).get;
