// Generated by CoffeeScript 2.6.1
var childProcess, fs, installData, pathLib;

fs = require("fs-extra");

installData = require("../../install_data");

pathLib = require("path");

childProcess = require("child_process");

module.exports = (server) => {
  return server.route({
    method: "post",
    path: "/database/init",
    handler: async function(req, h) {
      var err, installed;
      try {
        installed = (await (async function() {
          try {
            return JSON.parse((await fs.readFile(pathLib.resolve("./installed.json"))));
          } catch (error) {
            err = error;
            return false;
          }
        })());
        if (!installed) {
          return {
            ok: false,
            msg: "为找到安装配置，请重建安装配置文件"
          };
        }
        await fs.chmod(pathLib.resolve("../bash/initdb.sh"), 0o755);
        if (installData.database) {
          installData.database.kill();
          installData.database = null;
        }
        console.log("开始安装数据库");
        if (installData.database == null) {
          installData.database = new installData.Process(childProcess.spawn("/bin/bash", ["-c", `'./initdb.sh --dbName ${installed.dbName} --dbUser ${installed.dbUser} --dbPassword ${installed.dbPassword}'`], {
            shell: true,
            cwd: pathLib.resolve("../bash")
          }));
        }
        return {
          ok: true,
          msg: "数据库已经开始安装"
        };
      } catch (error) {
        err = error;
        console.log(err);
        return {
          ok: false,
          msg: "服务器内部错误"
        };
      }
    }
  });
};
