// Generated by CoffeeScript 2.6.1
var QueryTypes, childProcess, fs, installData, pathLib;

fs = require("fs-extra");

pathLib = require("path");

installData = require("../../install_data");

childProcess = require("child_process");

({QueryTypes} = require("sequelize"));

module.exports = (server) => {
  return server.route({
    method: "post",
    path: "/database/roles/del/{oid}",
    options: {
      validate: {
        params: Joi.object({
          oid: Joi.number().min(1).required()
        })
      }
    },
    handler: async function(req, h) {
      var data, err, par, que, role;
      try {
        par = req.params;
        que = req.payload;
        if (!installData.seq) {
          return {
            ok: false,
            msg: "未连接到数据库，请启动服务"
          };
        }
        if (!par.oid) {
          return {
            ok: false,
            msg: "请指定oid"
          };
        }
        role = (await installData.seq.query("SELECT oid,rolename FROM pg_roles WHERE oid=?", {
          type: QueryTypes.SELECT,
          replacements: [par.oid]
        }));
        if (!role) {
          return {
            ok: false,
            msg: "角色不存在"
          };
        }
        data = (await installData.seq.query("DROP ROLE ?", {
          type: QueryTypes.RAW,
          replacements: [role[0].rolename]
        }));
        console.log(data);
        return {
          ok: true,
          data: data,
          msg: `删除数据库角色${role[0].rolename}成功`
        };
      } catch (error) {
        err = error;
        console.log(err);
        return {
          ok: false,
          msg: "服务器内部错误"
        };
      }
    }
  });
};
