// Generated by CoffeeScript 2.6.1
var Iron, childProcess, fs, installData, pathLib;

fs = require("fs-extra");

installData = require("../../install_data");

Iron = require("@hapi/iron");

pathLib = require("path");

childProcess = require("child_process");

module.exports = (server) => {
  return server.route({
    method: "post",
    path: "/database/stop",
    handler: async function(req, h) {
      var err, tmp;
      try {
        installData.database.send("/Users/miao/pgsql/bin/pg_ctl -D /Users/miao/pgsql/data stop");
        tmp = (await new Promise((res, rej) => {
          return childProcess.exec("pkill -f postgres", function(err, stdout, stderr) {
            return res(JSON.stringify({
              exec: "pkill -f postgres",
              err: err,
              stdout: stdout,
              stderr: stderr
            }, null, "\t"));
          });
        }));
        installData.database.log(tmp);
        installData.database.log("已用上述命令试图结束全系统postgre服务");
        installData.database.kill();
        return {
          ok: true,
          msg: "停止命令已发送"
        };
      } catch (error) {
        err = error;
        console.log(err);
        return {
          ok: false,
          msg: "服务器内部错误"
        };
      }
    }
  });
};
