// Generated by CoffeeScript 2.6.1
var QueryTypes, childProcess, fs, installData, pathLib;

fs = require("fs-extra");

pathLib = require("path");

installData = require("../../install_data");

childProcess = require("child_process");

({QueryTypes} = require("sequelize"));

module.exports = (server) => {
  return server.route({
    method: "post",
    path: "/database/drop",
    options: {
      validate: {
        payload: Joi.object({
          dbName: Joi.string()
        })
      }
    },
    handler: async function(req, h) {
      var data, err, list, que;
      try {
        que = req.payload;
        if (dbName === 'template0' || dbName === 'template1' || dbName.startsWith('pg_')) {
          return {
            ok: false,
            msg: "不能删除内部的数据库"
          };
        }
        if (!installData.seq) {
          return {
            ok: false,
            msg: "未连接到数据库，请启动服务"
          };
        }
        list = (await installData.seq.query("SELECT datname FROM pg_database WHERE datistemplate = false AND datname = ?;", {
          type: QueryTypes.SELECT,
          replacements: [que.dbName]
        }));
        if (list.length === 0) {
          return {
            ok: false,
            msg: "数据库不存在"
          };
        }
        data = (await installData.seq.query("DROP DATABASE ?;", {
          type: QueryTypes.RAW,
          replacements: [que.dbName]
        }));
        return {
          ok: true,
          data: data,
          msg: `创建数据库${成功}`
        };
      } catch (error) {
        err = error;
        console.log(err);
        return {
          ok: false,
          msg: "服务器内部错误"
        };
      }
    }
  });
};
