// Generated by CoffeeScript 2.6.1
var cacheOpera;

cacheOpera = require("./cacheOpera");

module.exports = {
  method: "post",
  path: "/api/posts/lock/{pid}",
  options: {
    validate: {
      params: Joi.object({
        pid: Joi.string().pattern(/^\d+$/).required()
      })
    }
  },
  handler: async function(req, h) {
    var auth, author, db, err, level, pid, post, que;
    db = req.server.db;
    que = req.payload;
    auth = req.auth.credentials;
    pid = 1 * req.params.pid;
    level = null;
    try {
      if (auth.icat_users_extend.power < 80) {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
      post = (await db.icat_posts.findOne({
        attributes: ["pid", "isLock", "linkid", "uid"],
        where: {
          pid: pid
        }
      }));
      if (!post) {
        return {
          ok: false,
          msg: "帖子不存在"
        };
      }
      author = (await db.icat_users_extend.findOne({
        attributes: ["uid", "power"],
        where: {
          uid: post.uid
        }
      }));
      if (author) {
        if (auth.icat_users_extend.power < author.power) {
          return {
            ok: false,
            msg: "帖子作者的权限大于你的权限哦"
          };
        }
      }
      post.isLock = level = post.isLock > 0 ? 0 : 1;
      await post.save();
      
      //清除缓存表
      await cacheOpera.clean(db, post);
      return {
        ok: true,
        msg: "锁定/解锁成功",
        level: level
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
