// Generated by CoffeeScript 2.6.1
var cacheOpera;

cacheOpera = require("./cacheOpera");

module.exports = {
  method: "post",
  path: "/api/posts/top/{pid}",
  options: {
    validate: {
      params: Joi.object({
        pid: Joi.string().pattern(/^\d+$/).required()
      })
    }
  },
  handler: async function(req, h) {
    var auth, db, err, level, pid, post, que;
    db = req.server.db;
    que = req.payload;
    auth = req.auth.credentials;
    pid = 1 * req.params.pid;
    level = null;
    try {
      post = (await db.icat_posts.findOne({
        attributes: ["pid", "isTop", "linkid"],
        where: {
          pid: pid
        }
      }));
      if (auth.icat_users_extend.power >= 80) {
        post.isTop = level = post.isTop > 0 ? 0 : post.contentType === "score" ? 10 : 1; //如果是评分
        await post.save();
        
        //清除缓存表
        await cacheOpera.clean(db, post);
        return {
          ok: true,
          msg: "置顶/取消置顶成功",
          level: level
        };
      } else {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
