// Generated by CoffeeScript 2.6.1
/*
pid
*/
var Op, cacheOpera;

({Op} = require("sequelize"));

cacheOpera = require("./cacheOpera");

module.exports = {
  method: "post",
  path: "/api/posts/readPerm/{pid}",
  options: {
    validate: {
      params: Joi.object({
        pid: Joi.string().pattern(/^\d+$/).required()
      }),
      payload: Joi.object({
        perm: Joi.number().integer().min(0).max(4).required()
      })
    }
  },
  //0 关闭权限控制
  //1 仅自己可见
  //2 上级可见
  //3 回复者可见
  //4 上级和回复者可见

  //5 指定用户可见
  //6 指定用户组可见

  //7 回复仅自己可见（对板块而言即隐藏）
  //8 回复指定用户可见
  //9 回复指定用户组可见
  handler: async function(req, h) {
    var auth, db, err, pid, post, que;
    try {
      db = req.server.db;
      que = req.payload;
      auth = req.auth.credentials;
      pid = Number(req.params.pid);
      post = (await db.icat_posts.findOne({
        attributes: ["pid", "uid", "isPrivate", "contentType", "linkid"],
        where: {
          pid: pid
        }
      }));
      if (!["bbcode", "markdown"].find((item) => {
        return item === post.contentType;
      })) {
        return {
          ok: false,
          msg: "不支持的帖子类型"
        };
      }
      if (!post) {
        return {
          ok: false,
          msg: "找不到帖子"
        };
      }
      if (!(post.uid === (auth != null ? auth.uid : void 0) || auth.icat_users_extend.power >= 90)) {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
      post.isPrivate = que.perm;
      await post.save();
      //清除缓存表
      await cacheOpera.clean(db, post);
      return {
        ok: true,
        msg: "权限修改成功"
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
