// Generated by CoffeeScript 2.6.1
/*
pid
*/
var cacheOpera;

cacheOpera = require("./cacheOpera");

module.exports = {
  method: "post",
  path: "/api/posts/like/{pid}",
  options: {
    validate: {
      params: Joi.object({
        pid: Joi.string().pattern(/^\d+$/).required()
      })
    }
  },
  handler: async function(req, h) {
    var auth, db, err, pid, post, que, tmp;
    try {
      db = req.server.db;
      que = req.payload;
      auth = req.auth.credentials;
      pid = Number(req.params.pid);
      post = pawait(db.icat_posts.update({
        likes: (tmp = ((await db.icat_posts.findOne({
          where: {
            pid: pid
          }
        }))).likes) ? (tmp = JSON.parse(tmp))[auth.uid] ? (delete tmp[auth.uid], JSON.stringify(tmp)) : (tmp[auth.uid] = auth.user, JSON.stringify(tmp)) : (tmp = {}, tmp[auth.uid] = auth.user, JSON.stringify(tmp))
      }, {
        where: {
          pid: pid
        }
      }));
      //清除缓存表
      await cacheOpera.clean(db, post);
      return {
        ok: true,
        msg: "赞操作成功"
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
