// Generated by CoffeeScript 2.6.1
var createAPI;

createAPI = require("../../tools/api/createAPI");

module.exports = createAPI("post", {
  idName: "pid",
  cnName: "帖子元数据",
  getPath: "/api/posts/raw/get/{pid?}",
  power: 90
}).get;
