// Generated by CoffeeScript 2.6.1
var cacheOpera;

cacheOpera = require("./cacheOpera");

module.exports = {
  method: "post",
  path: "/api/posts/hide/{pid}",
  options: {
    validate: {
      params: Joi.object({
        pid: Joi.string().pattern(/^\d+$/).required()
      }),
      payload: Joi.object({
        nested: Joi.number().default(0)
      })
    }
  },
  handler: async function(req, h) {
    var auth, author, db, err, fn, level, pid, post, que, t;
    db = req.server.db;
    que = req.payload;
    auth = req.auth.credentials;
    pid = 1 * req.params.pid;
    level = null;
    try {
      if (auth.icat_users_extend.power < 80) {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
      post = (await db.icat_posts.findOne({
        attributes: ["pid", "isHide", "linkid", "uid"],
        where: {
          pid: pid
        }
      }, {
        transaction: t
      }));
      if (!post) {
        return {
          ok: false,
          msg: "帖子不存在"
        };
      }
      author = (await db.icat_users_extend.findOne({
        attributes: ["uid", "power"],
        where: {
          uid: post.uid
        }
      }));
      if (author) {
        if (auth.icat_users_extend.power < author.power) {
          return {
            ok: false,
            msg: "帖子作者的权限大于你的权限哦"
          };
        }
      }
      t = (await db.mysql.transaction());
      post.isHide = level = post.isHide > 0 ? 0 : 1;
      await post.save({
        transaction: t
      });
      //递归修改
      if (que.nested) {
        fn = async function(post, level) {
          var child, children, i, len;
          post.isHide = level;
          await post.save({
            transaction: t
          });
          children = (await db.icat_posts.findAll({
            attributes: ["pid", "isHide", "linkid"],
            where: {
              linkid: post.pid
            }
          }, {
            transaction: t
          }));
          for (i = 0, len = children.length; i < len; i++) {
            child = children[i];
            await fn(child, level);
          }
          return (await post.save({
            transaction: t
          }));
        };
        await fn(post, level);
      }
      //清除缓存表
      await cacheOpera.clean(db, post);
      await t.commit();
      return {
        ok: true,
        msg: "隐藏/显示成功",
        level: level
      };
    } catch (error) {
      err = error;
      console.log(err);
      await t.rollback();
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
