// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "post",
  path: "/api/posts/perm/{pid}",
  options: {
    validate: {
      params: Joi.object({
        pid: Joi.string().pattern(/^\d+$/).required()
      }),
      payload: Joi.object
    }
  },
  handler: function(req, h) {
    var auth, db, err, que;
    que = req.query;
    db = req.server.db;
    auth = req.auth.credentials;
    try {

    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
