// Generated by CoffeeScript 2.6.1
var createAPI, setPayload;

createAPI = require("../../tools/api/createAPI");

setPayload = {
  contentType: Joi.string(),
  content: Joi.string(),
  linkid: Joi.string(),
  createTimestamp: Joi.number(),
  updateTimestamp: Joi.number(),
  isTop: Joi.number(),
  idGood: Joi.number(),
  isLock: Joi.number(),
  isPrivate: Joi.number(),
  isHide: Joi.number(),
  needCheck: Joi.number(),
  replyCalc: Joi.number(),
  loveCalc: Joi.number(),
  starCalc: Joi.number(),
  calcTimestamp: Joi.number()
};

module.exports = createAPI("post", {
  idName: "pid",
  cnName: "帖子元数据",
  setPath: "/api/posts/raw/set/{pid?}",
  setFields: Object.keys(setPayload),
  setPayload: setPayload,
  setPower: 90
}).set;
