// Generated by CoffeeScript 2.6.1
var Op;

({Op} = require("sequelize"));

module.exports = {
  clean: async function(db, post) {
    var delCacheLinkids, delCachePids, err, where1, where2;
    try {
      where1 = {
        [Op.or]: [
          {
            que: {
              pid: {
                [Op.or]: [post.pid,
          post.linkid]
              }
            }
          },
          {
            par: {
              pid: {
                [Op.or]: [post.pid,
          post.linkid]
              }
            }
          }
        ]
      };
      where2 = {
        que: {
          linkid: {
            [Op.or]: [post.pid, post.linkid]
          }
        }
      };
      delCachePids = (await db.icat_cache_pids.destroy({
        where: where1
      }));
      return delCacheLinkids = (await db.icat_cache_linkids.destroy({
        where: where2
      }));
    } catch (error) {
      err = error;
      throw err;
    }
  }
};
