// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "post",
  path: "/api/tasks/del/{taskid}",
  options: {
    validate: {
      params: Joi.object({
        taskid: Joi.string().pattern(/^\d+$/)
      })
    }
  },
  handler: async function(req, h) {
    var auth, db, err, que, task, taskid;
    try {
      db = req.server.db;
      que = req.payload;
      auth = req.auth.credentials;
      taskid = Number(req.params.taskid);
      if (auth.icat_users_extend.power < 90) {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
      task = (await db.icat_tasks.findOne({
        where: {
          taskid: taskid
        }
      }));
      if (!task) {
        return {
          ok: false,
          msg: "任务不存在"
        };
      }
      //清除任务记录，用户的任务记录在积分日志有保留
      await db.icat_stats.destroy({
        where: {
          taskid: taskid
        }
      });
      await task.destroy();
      return {
        ok: true,
        msg: "任务删除成功"
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
