// Generated by CoffeeScript 2.6.1
var Process, childProcess, luxon;

luxon = require("luxon");

childProcess = require("child_process");

Process = class {
  constructor(process) {
    if (!process) {
      throw new Error("需要childProcess的实例 new Process(process)");
    }
    this.logs = [];
    this.process = process;
    this.process.stdout.on("data", (data) => {
      return this.log(data);
    });
    this.process.stderr.on("data", (data) => {
      return this.log(data, "stderr");
    });
    this.process.on("exit", () => {
      return this.log("服务退出", "exit");
    });
  }

  kill() {
    this.process.kill('SIGTERM');
    return this.process.killed = true;
  }

  log(data, type) {
    var log, timeStr;
    timeStr = luxon.DateTime.local().toFormat("yyyy/MM/dd HH:mm:ss");
    if (type === "stderr") {
      type = "错误";
    } else if (type === "exit") {
      type = "退出";
    } else if (type === "send") {
      type = "发送";
    } else {
      type = "信息";
    }
    this.logs.push(log = {
      time: Date.now(),
      timeStr: timeStr,
      info: `[${timeStr}][${type}]${data.toString()}`,
      data: data.toString(),
      buffer: data,
      type: type
    });
    console.log(log.info);
    if (this.logs.length > 200) {
      return this.logs.shift();
    }
  }

  send(cmd) {
    return this.process.stdin.write(cmd + "\n");
  }

};

module.exports = {
  Process: Process,
  pwdErrorCount: 0,
  timer: null,
  miao: null,
  database: null,
  command: null,
  seq: null
};
