// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    tagid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    type: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: "tag"
    },
    description: {
      type: DataTypes.STRING
    },
    count: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    order: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    parent: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    }
  };
  return mysql.define("icat_tags", data, {
    freezeTableName: true
  });
};
