// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    uextid: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    uid: {
      type: DataTypes.INTEGER,
      allowNull: false,
      unique: true
    },
    user: {
      type: DataTypes.STRING,
      allowNull: false
    },
    //unique:yes
    credit: {
      type: DataTypes.FLOAT,
      defaultValue: 0
    },
    group: {
      type: DataTypes.STRING,
      allowNull: false
    },
    power: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    signTimestamp: {
      type: DataTypes.BIGINT,
      allowNull: false
    },
    loginTimestamp: {
      type: DataTypes.BIGINT,
      allowNull: false
    },
    name: DataTypes.STRING,
    avatar: DataTypes.TEXT,
    homeDir: DataTypes.TEXT({
      defaultValue: ""
    }),
    email: DataTypes.STRING,
    emailVerify: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    sex: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    age: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    brithday: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW
    },
    introduction: DataTypes.TEXT,
    qq: DataTypes.STRING,
    wechat: DataTypes.STRING,
    ip: DataTypes.STRING,
    lastLoginIp: DataTypes.STRING,
    postCount: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    replyCount: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    likeCount: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    favoriteCount: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    friendCount: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    salt: {
      type: DataTypes.STRING
    },
    dzUid: {
      type: DataTypes.INTEGER
    }
  };
  return mysql.define("icat_users_extend", data, {
    indexes: [
      ...(["uid",
      "user",
      "name",
      "email",
      "emailVerify",
      "dzUid",
      "signTimestamp",
      "loginTimestamp",
      "ip",
      "lastLoginIp",
      "salt",
      "wechat",
      "qq",
      "sex",
      "age",
      "group",
      "power",
      "credit"].map((item) => {
        return {
          fields: [item]
        };
      }))
    ],
    freezeTableName: true
  });
};
