// Generated by CoffeeScript 2.6.1
var DataTypes, INTEGER;

({DataTypes, INTEGER} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    pid: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      allowNull: false,
      primaryKey: true
    },
    uid: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    author: {
      type: DataTypes.STRING,
      allowNull: false
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false
    },
    content: {
      type: DataTypes.TEXT("long"),
      allowNull: false
    },
    contentType: {
      type: DataTypes.STRING,
      defaultValue: "markdown"
    },
    likes: {
      type: DataTypes.TEXT,
      defaultValue: "{}"
    },
    createTime: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW
    },
    finallyTime: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW
    },
    createTimestamp: {
      type: DataTypes.BIGINT,
      allowNull: false
    },
    updateTimestamp: {
      type: DataTypes.BIGINT,
      allowNull: false
    },
    linkid: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    isTop: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    isGood: {
      type: DataTypes.INTEGER,
      defaultValue: 0 //精华等级
    },
    isLock: {
      type: DataTypes.INTEGER,
      defaultValue: 0 //是否锁定
    },
    isPrivate: { //仅自己可见
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    isHide: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    globalTop: { //全局置顶 #单独写api读取
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    blockTop: { //板块置顶
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    needCheck: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    timeDelta: { //时间变更量，小时单位，用于帖子提前或滞后
      type: DataTypes.BIGINT,
      defaultValue: 0
    },
    block: { //废弃
      type: DataTypes.INTEGER
    },
    tags: { //废弃
      type: DataTypes.TEXT //json
    },
    views: { //浏览量
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    linkChain: { //本来应该要设置不允许空的，但是为了兼容旧数据
      type: DataTypes.STRING
    },
    replyCalc: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    loveCalc: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    starCalc: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    calcTimestamp: {
      type: DataTypes.BIGINT,
      defaultValue: 0
    },
    dzUid: {
      type: DataTypes.INTEGER
    },
    dzFid: { //板块id/分区id
      type: DataTypes.INTEGER
    },
    dzFup: { //上级板块id
      type: DataTypes.INTEGER
    },
    dzTid: {
      type: DataTypes.INTEGER
    },
    dzPid: {
      type: DataTypes.INTEGER
    }
  };
  return mysql.define("icat_posts", data, {
    indexes: [
      ...(["uid",
      "linkid",
      "author",
      "title",
      "contentType",
      "dzUid",
      "dzFid",
      "dzFup",
      "dzTid",
      "dzPid",
      "timeDelta",
      "createTimestamp",
      "updateTimestamp",
      "isTop",
      "isGood",
      "isLock",
      "isPrivate",
      "isHide",
      "globalTop",
      "blockTop",
      "needCheck",
      "views",
      "linkChain"].map((item) => {
        return {
          fields: [item]
        };
      })),
      {
        fields: ["linkid",
      "isTop",
      "pid"]
      },
      {
        fields: ["isTop",
      "pid"]
      },
      {
        fields: ["pid",
      "isTop"]
      },
      {
        fields: ["uid",
      "linkid"]
      },
      {
        fields: ["linkid",
      "uid"]
      }
    ],
    /*
    {
      fields:["content"]
      type:"fulltext"
    }
    */
    freezeTableName: true
  });
};
