// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data, db_icat_credits;
  data = {
    creditid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    unit: { //单位
      type: DataTypes.STRING,
      allowNull: false
    },
    rate: { //兑换比率
      type: DataTypes.DOUBLE,
      allowNull: false,
      defaultValue: 0
    },
    isUse: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 1
    },
    allowScore: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    }
  };
  db_icat_credits = mysql.define("icat_credits", data, {
    indexes: [
      ...(["isUse",
      "allowScore",
      "name"].map((item) => {
        return {
          fields: [item]
        };
      }))
    ],
    freezeTableName: true
  });
  /*
  db_icat_credits.sync({
    alter:true
  })
  */
  return db_icat_credits;
};
