// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    fileid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    uid: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    user: {
      type: DataTypes.STRING,
      allowNull: false
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    defaultName: { //带扩展名
      type: DataTypes.STRING,
      allowNull: false
    },
    extName: {
      type: DataTypes.STRING,
      allowNull: false
    },
    type: {
      type: DataTypes.STRING,
      allowNull: false
    },
    size: {
      type: DataTypes.DOUBLE,
      allowNull: false
    },
    directory: {
      type: DataTypes.TEXT,
      allowNull: false
    },
    path: { //相对路径
      type: DataTypes.TEXT,
      allowNull: false
    },
    pathZip: { //缩略图等
      type: DataTypes.TEXT,
      allowNull: true
    },
    dzPath: {
      type: DataTypes.TEXT
    },
    md5: {
      type: DataTypes.STRING,
      allowNull: false
    },
    timestamp: {
      type: DataTypes.BIGINT,
      allowNull: false
    },
    isSystem: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    }
  };
  return mysql.define("icat_files", data, {
    indexes: [
      ...(["uid",
      "user",
      "name",
      "defaultName",
      "extName",
      "type",
      "size",
      "md5",
      "timestamp",
      "isSystem"].map((item) => {
        return {
          fields: [item]
        };
      }))
    ],
    freezeTableName: true
  });
};
