// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    varid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    uid: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    user: {
      type: DataTypes.STRING,
      allowNull: false
    },
    key: {
      type: DataTypes.STRING,
      allowNull: false
    },
    value: {
      type: DataTypes.TEXT("long"),
      allowNull: false,
      get: function() {
        return JSON.parse(this.getDataValue("value"));
      },
      set: function(value) {
        return this.setDataValue("value", JSON.stringify(value));
      }
    },
    power: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    sign: {
      type: DataTypes.TEXT
    }
  };
  return mysql.define("icat_vars", data, {
    indexes: [
      ...(["uid",
      "user",
      "key",
      "power"].map((item) => {
        return {
          fields: [item]
        };
      }))
    ],
    freezeTableName: true
  });
};
