// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes, DataTypes, DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    eventid: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      allowNull: false,
      primaryKey: true
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    showName: {
      type: DataTypes.STRING
    },
    type: {
      type: DataTypes.STRING,
      allowNull: false
    },
    description: {
      type: DataTypes.STRING
    },
    note: {
      type: DataTypes.TEXT
    },
    url: {
      type: DataTypes.STRING
    },
    x: {
      type: DataTypes.FLOAT
    },
    y: {
      type: DataTypes.FLOAT
    },
    w: {
      type: DataTypes.FLOAT
    },
    h: {
      type: DataTypes.FLOAT
    },
    imgX: {
      type: DataTypes.FLOAT
    },
    imgY: {
      type: DataTypes.FLOAT
    },
    imgZeroX: {
      type: DataTypes.FLOAT
    },
    imgZeroY: {
      type: DataTypes.FLOAT
    },
    imgW: {
      type: DataTypes.FLOAT
    },
    imgH: {
      type: DataTypes.FLOAT
    },
    boxSize: {
      type: DataTypes.FLOAT
    },
    passAll: {
      type: DataTypes.INTEGER
    },
    opacity: {
      type: DataTypes.FLOAT
    },
    zIndex: {
      type: DataTypes.INTEGER
    },
    config: {
      type: DataTypes.TEXT,
      get: function() {
        return JSON.parse(this.getDataValue("config"));
      },
      set: function(value) {
        return this.setDataValue("config", JSON.stringify(value));
      }
    },
    script: {
      type: DataTypes.STRING
    }
  };
  return mysql.define("icat_events", data, {
    indexes: [
      ...(["name"].map((item) => {
        return {
          fields: [item]
        };
      }))
    ],
    freezeTableName: true
  });
};
