// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    goodid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    type: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: "普通物品"
    },
    icon: {
      type: DataTypes.STRING
    },
    description: {
      type: DataTypes.TEXT
    },
    consumable: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 1
    },
    disposable: { //是否一次性使用
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    expires: { //有效期，毫秒
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    storage: { //库存
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 100
    },
    purchaseLimit: { //限购 -1表示不限制
      type: DataTypes.INTEGER,
      defaultValue: -1
    },
    config: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: "{}",
      get: function() {
        return JSON.parse(this.getDataValue("config"));
      },
      set: function(value) {
        return this.setDataValue("config", JSON.stringify(value));
      }
    }
  };
  return mysql.define("icat_goods", data, {
    freezeTableName: true,
    indexes: [
      ...(["name",
      "type"].map((item) => {
        return {
          fields: [item]
        };
      }))
    ]
  });
};
