// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    ntceid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    /* senderId:{
         type: DataTypes.INTEGER
         allowNull:no
       } */
    sender: {
      type: DataTypes.STRING,
      allowNull: false
    },
    /* receiverId:{
         type: DataTypes.INTEGER
         allowNull:no
       }  */
    receiver: {
      type: DataTypes.STRING,
      allowNull: false
    },
    msgType: {
      type: DataTypes.STRING,
      allowNull: false
    },
    msgAction: {
      type: DataTypes.STRING,
      allowNull: false
    },
    msgContent: {
      type: DataTypes.TEXT,
      allowNull: false
    },
    sendTime: { //这里改用了timestamp时间戳bigint本来是string
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: function() {
        return Date.now();
      }
    },
    readTime: {
      type: DataTypes.BIGINT
    }
  };
  return mysql.define("icat_notices", data, {
    indexes: [
      ...(["sender",
      "receiver",
      "msgType",
      "msgAction",
      "sendTime",
      "readTime"].map((item) => {
        return {
          fields: [item]
        };
      }))
    ],
    freezeTableName: true
  });
};
