// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    testid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      identity: true
    }
  };
  return mysql.define("icat_tests", data, {
    freezeTableName: true
  });
};
