// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    gid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    color: {
      type: DataTypes.STRING,
      defaultValue: "#333"
    },
    level: { //星星等级
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    type: {
      type: DataTypes.STRING, //管理组，内置组，会员组，特殊组
      defaultValue: "内置组"
    },
    icon: {
      type: DataTypes.STRING,
      defaultValue: ""
    },
    point: {
      type: DataTypes.INTEGER, //积分范围
      defaultValue: 0
    }
  };
  return mysql.define("icat_groups", data, {
    freezeTableName: true
  });
};
