// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    creditCalcid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    uid: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    user: {
      type: DataTypes.STRING,
      allowNull: false
    },
    creditid: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    creditName: {
      type: DataTypes.STRING,
      allowNull: false
    },
    calc: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    freeze: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    action: {
      type: DataTypes.STRING,
      allowNull: false
    },
    type: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: "system" //system pay user
    },
    note: {
      type: DataTypes.TEXT
    },
    timestamp: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: Date.now()
    },
    //如果是订单
    payState: { //支付状态
      type: DataTypes.INTEGER
    },
    //1 已下单 2 已支付 3 已发货
    payPlatform: {
      type: DataTypes.STRING
    },
    payPlatfromUser: {
      type: DataTypes.STRING
    },
    paySystemOrderNum: {
      type: DataTypes.STRING
    },
    payPlatformOrderNum: {
      type: DataTypes.STRING
    },
    paySubject: {
      type: DataTypes.STRING
    },
    payDescription: {
      type: DataTypes.TEXT
    }
  };
  return mysql.define("icat_credits_calc", data, {
    indexes: [
      ...(["uid",
      "user",
      "creditid",
      "creditName",
      "type",
      "action",
      "paySystemOrderNum",
      "payPlatformOrderNum",
      "timestamp"].map((item) => {
        return {
          fields: [item]
        };
      }))
    ],
    freezeTableName: true
  });
};
