// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    taskid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    order: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    linkid: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    beforeTask: {
      type: DataTypes.INTEGER
    },
    type: { //rpg bbs 用于排序？
      type: DataTypes.STRING,
      allowNull: false
    },
    // 发新贴thread、回复reply、点赞like、签到
    action: {
      type: DataTypes.STRING,
      allowNull: false
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    description: {
      type: DataTypes.TEXT
    },
    startTimestamp: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    endTimestamp: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    cycleTimestamp: {
      type: DataTypes.BIGINT,
      allowNull: false,
      defaultValue: 0
    },
    target: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    extra: {
      type: DataTypes.TEXT,
      allowNull: false,
      get: function() {
        return JSON.parse(this.getDataValue("extra"));
      },
      set: function(value) {
        return this.setDataValue("extra", JSON.stringify(value));
      }
    },
    creditid: {
      type: DataTypes.INTEGER,
      defaultValue: 1
    },
    credit: {
      type: DataTypes.DOUBLE
    },
    creditid2: {
      defaultValue: 1,
      type: DataTypes.INTEGER
    },
    credit2: {
      type: DataTypes.DOUBLE
    },
    creditid3: {
      defaultValue: 1,
      type: DataTypes.INTEGER
    },
    credit3: {
      type: DataTypes.DOUBLE
    },
    goodid: {
      defaultValue: 1,
      type: DataTypes.INTEGER
    },
    goodNum: {
      type: DataTypes.DOUBLE
    },
    goodid2: {
      defaultValue: 1,
      type: DataTypes.INTEGER
    },
    goodNum2: {
      type: DataTypes.DOUBLE
    },
    goodid3: {
      defaultValue: 1,
      type: DataTypes.INTEGER
    },
    goodNum3: {
      type: DataTypes.DOUBLE
    },
    level: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 1
    },
    freeze: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 1
    },
    useRandom: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 1
    },
    timestamp: {
      type: DataTypes.BIGINT,
      allowNull: false
    }
  };
  return mysql.define("icat_tasks", data, {
    freezeTableName: true
  });
};
