// Generated by CoffeeScript 2.6.1
var DataTypes;

({DataTypes} = require('sequelize'));

module.exports = (mysql) => {
  var data;
  data = {
    compid: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    type: {
      type: DataTypes.INTEGER,
      allowNull: false //1.当前页组件 2.链接，本窗口 3.链接，新窗口
    },
    path: {
      type: DataTypes.STRING,
      allowNull: false
    },
    icon: {
      type: DataTypes.STRING
    },
    extra: {
      type: DataTypes.TEXT,
      allowNull: false,
      get: function() {
        return JSON.parse(this.getDataValue("extra"));
      },
      set: function(value) {
        return this.setDataValue("extra", JSON.stringify(value));
      }
    },
    note: {
      type: DataTypes.STRING
    }
  };
  return mysql.define("icat_comps", data, {
    indexes: [
      ...(["name"].map((item) => {
        return {
          fields: [item]
        };
      }))
    ],
    freezeTableName: true
  });
};
