// Generated by CoffeeScript 2.6.1
var Iron, fs, installData, pathLib;

fs = require("fs-extra");

installData = require("../../install_data");

Iron = require("@hapi/iron");

pathLib = require("path");

module.exports = (server) => {
  return server.route({
    method: "post",
    path: "/command/send",
    options: {
      validate: {
        payload: Joi.object({
          cmd: Joi.string()
        })
      }
    },
    handler: function(req, h) {
      var err, que, ref;
      try {
        que = req.payload;
        if (((ref = installData.command) != null ? ref.process : void 0) == null) {
          return {
            ok: false,
            msg: "服务进程不存在"
          };
        }
        installData.command.log(que.cmd);
        installData.command.send(que.cmd, "send");
        return {
          //installData.pg.process.stdin.end()
          ok: true,
          msg: "命令执行成功"
        };
      } catch (error) {
        err = error;
        console.log(err);
        return {
          ok: false,
          msg: "服务器内部错误"
        };
      }
    }
  });
};
