// Generated by CoffeeScript 2.6.1
var childProcess, fs, installData, pathLib;

fs = require("fs-extra");

installData = require("../../install_data");

pathLib = require("path");

childProcess = require("child_process");

module.exports = (server) => {
  return server.route({
    method: "post",
    path: "/command/start",
    handler: function(req, h) {
      var err;
      try {
        if (installData.command == null) {
          installData.command = new installData.Process(childProcess.spawn("/bin/bash", [], {
            shell: true,
            cwd: pathLib.resolve("../bash")
          }));
        }
        return {
          //stdio:["pipe","pipe","pipe"]
          ok: true,
          msg: "命令服务已启动"
        };
      } catch (error) {
        err = error;
        console.log(err);
        return {
          ok: false,
          msg: "服务器内部错误"
        };
      }
    }
  });
};
