// Generated by CoffeeScript 2.6.1
var fs, pathLib;

fs = require("fs-extra");

pathLib = require("path");

module.exports = async function(server) {
  var checkDir, err, file, file2, files, files2, i, isDir, len, results, root, route;
  try {
    root = pathLib.resolve("./apis") + "/";
    files = (await fs.readdir(root));
    checkDir = async function(path) {
      return ((await fs.stat(root + path))).isDirectory();
    };
    results = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      isDir = (await checkDir(file));
      if (isDir) {
        files2 = (await fs.readdir(root + file));
        results.push((await (async function() {
          var j, len1, results1;
          results1 = [];
          for (j = 0, len1 = files2.length; j < len1; j++) {
            file2 = files2[j];
            if (file2.match(/^api_/) && file2.match(/.js$/)) {
              //检测是否是合法路由JSON
              /*
              console.log {
                file
                file2
              }
              */
              if (route = require(`./${file}/${file2}`)) {
                results1.push((await route(server)));
              } else {
                results1.push(void 0);
              }
            } else {
              results1.push(void 0);
            }
          }
          return results1;
        })()));
      } else {
        results.push(void 0);
      }
    }
    return results;
  } catch (error) {
    err = error;
    console.log(file2);
    return console.log(err);
  }
};
