// Generated by CoffeeScript 2.6.1
var createAPI, getFindAllWhere;

createAPI = require("../../tools/api/createAPI");

getFindAllWhere = function(sendParams) {
  var que;
  ({que} = sendParams);
  return {
    type: que.type
  };
};

module.exports = createAPI("group", {
  idName: "gid",
  cnName: "用户组",
  getFindAll: function() {
    return {
      order: [["point", "ASC"]]
    };
  },
  getFindAllWhere: getFindAllWhere,
  getQuery: {
    type: Joi.string().valid("会员组", "管理组", "特殊组", "内置组")
  },
  getAllCountWhere: getFindAllWhere
}).get;
