// Generated by CoffeeScript 2.6.1
var createAPI, setPayload;

createAPI = require("../../tools/api/createAPI");

setPayload = {
  gid: Joi.number(),
  name: Joi.string().required(),
  color: Joi.string().pattern(/^#[a-zA-Z0-9]{3,6}$/).default("#333").allow("").allow(null),
  level: Joi.number().default(0).allow(null),
  type: Joi.string().valid("会员组", "管理组", "特殊组", "内置组"),
  icon: Joi.string().allow("").allow(null),
  point: Joi.number().default(0).allow(null)
};

module.exports = createAPI("group", {
  idName: "gid",
  cnName: "用户组",
  setFields: Object.keys(setPayload),
  setPayload: setPayload
}).set;
