// Generated by CoffeeScript 2.6.1
var Op;

({Op} = require("sequelize"));

module.exports = {
  path: "/api/blocks/del/{pid}",
  method: "post",
  options: {
    validate: {
      params: Joi.object({
        pid: Joi.string().pattern(/^\d+$/).required()
      })
    }
  },
  handler: async function(req, h) {
    var auth, db, err, fn, pid, preDelPost, que, t;
    que = req.payload;
    db = req.server.db;
    auth = req.auth.credentials;
    t = (await db.mysql.transaction());
    pid = Number(req.params.pid);
    try {
      if (auth.icat_users_extend.power <= 90) {
        return {
          ok: false,
          msg: "权限不足"
        };
      }
      preDelPost = (await db.icat_posts.findOne({
        where: {
          contentType: {
            [Op.or]: ["block", "sysFile"]
          },
          pid: pid
        }
      }));
      if (!preDelPost) {
        return {
          ok: false,
          msg: "板块不存在"
        };
      }
      fn = async(pid) => {
        var i, len, post, posts, results;
        posts = (await db.icat_posts.findAll({
          where: {
            linkid: pid
          }
        }, {
          transaction: t
        }));
        results = [];
        for (i = 0, len = posts.length; i < len; i++) {
          post = posts[i];
          fn(post.pid);
          results.push((await post.destroy({
            transaction: t
          })));
        }
        return results;
      };
      await fn(pid);
      await preDelPost.destroy({
        transaction: t
      });
      await t.commit();
      return {
        ok: true,
        msg: "删除成功"
      };
    } catch (error) {
      err = error;
      console.log(err);
      await t.rollback();
      return {
        ok: false,
        msg: "删除失败，服务器异常"
      };
    }
  }
};
