// Generated by CoffeeScript 2.6.1
/*
  desc
  linkid
  limit
*/
var Op;

({Op} = require("sequelize"));

module.exports = {
  method: "get",
  path: "/api/blocks/get/{pid?}",
  options: {
    auth: false,
    validate: {
      params: Joi.object({
        pid: Joi.string().pattern(/^\d+$/)
      }),
      query: Joi.object({
        linkid: Joi.string().pattern(/^\d+$/).default(0),
        limit: Joi.number().max(150).default(8),
        offset: Joi.string().pattern(/^\d+$/),
        order: Joi.string().valid("desc", "asc"),
        contentType: Joi.string().valid("block", "sysFile", "both").default("both")
      })
    }
  },
  handler: async function(req, h) {
    var allCount, auth, data, db, err, que;
    try {
      db = req.server.db;
      que = req.query;
      auth = req.auth.credentials;
      // 注意参数类型为字符串
      data = (await db.icat_posts.findAll({
        where: {
          ...(req.params.pid ? {
            pid: req.params.pid
          } : void 0),
          contentType: que.contentType === "both" ? {
            [Op.or]: ["block", "sysFile"]
          } : que.contentType,
          linkid: Number(que.linkid)
        },
        order: [["isTop", "DESC"], ["pid", "ASC"]],
        ...(que.limit != null ? {
          limit: Number(que.limit)
        } : void 0),
        ...(que.offset != null ? {
          offset: Number(que.offset)
        } : void 0)
      }));
      allCount = (await db.icat_posts.count({
        where: {
          ...(req.params.pid ? {
            pid: req.params.pid
          } : void 0),
          contentType: que.contentType === "both" ? {
            [Op.or]: ["block", "sysFile"]
          } : que.contentType,
          linkid: Number(que.linkid)
        }
      }));
      //格式化content内容
      data.forEach((item) => {
        return item.content = JSON.parse(item.content);
      });
      //根据order排序
      data = data.sort((x1, x2) => {
        return Number(x1.content.order) - Number(x2.content.order);
      });
      if (req.params.pid) { //如果请求的是单个帖子且data[0]不存在
        if (!data[0]) {
          return {
            ok: false,
            msg: "未匹配到对应数据"
          };
        }
      }
      return {
        ok: true,
        msg: "获取板块列表成功",
        data: req.params.pid ? data[0] : data, //如果是单个数据，需要释放数组
        allCount: allCount
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
