// Generated by CoffeeScript 2.6.1
var db;

db = require("../db_main");

(async function() {
  var err, i, len, queryInterface, tableName, tableNames;
  try {
    await db.init();
    queryInterface = db.seq.getQueryInterface();
    tableNames = Object.keys(db.seq.models);
    for (i = 0, len = tableNames.length; i < len; i++) {
      tableName = tableNames[i];
      await (async(tableName) => {
        var info, infos, j, key, len1, ref, results;
        infos = (await queryInterface.describeTable(tableName));
        ref = Object.entries(infos);
        results = [];
        for (j = 0, len1 = ref.length; j < len1; j++) {
          [key, info] = ref[j];
          if (info.primaryKey) {
            console.log(`准备更新${tableName}_${key}_seq序列`);
            results.push((await db.seq.query(`select setval('"${tableName}_${key}_seq"', (select max(${tableName}."${key}") from ${tableName}))`)));
          } else {
            results.push(void 0);
          }
        }
        return results;
      })(tableName);
    }
    return console.log("===完成===");
  } catch (error) {
    err = error;
    return console.log(err);
  }
})();
