// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/api/vars/get/{key}",
  options: {
    validate: {
      params: Joi.object({
        key: Joi.string().token()
      })
    }
  },
  handler: async function(req, h) {
    var auth, data, db, err, que;
    que = req.query;
    db = req.server.db;
    auth = req.auth.credentials;
    try {
      data = (await db.icat_vars.findOne({
        where: {
          uid: auth.uid,
          key: req.params.key
        }
      }));
      if (data) {
        return {
          ok: true,
          data: data.value
        };
      } else {
        return {
          ok: true,
          msg: "没有对应的变量"
        };
      }
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
