// Generated by CoffeeScript 2.6.1
module.exports = {
  method: "get",
  path: "/api/press/get",
  options: {
    validate: {
      query: Joi.object({
        order: Joi.string().pattern(/desc|asc/i),
        offset: Joi.string().pattern(/\d/),
        limit: Joi.string().min(1).max(1)
      })
    },
    auth: false
  },
  handler: async function(req, h) {
    var allCount, data, db, err, que;
    que = req.query;
    db = req.server.db;
    try {
      data = (await db.icat_vars.findAll({
        where: {
          key: "press"
        },
        order: [...(que.order ? ["varid", Number(que.order)] : [])],
        ...(que.limit ? {
          limit: Number(que.limit)
        } : {
          limit: 8
        }),
        ...(que.offset ? {
          offset: Number(que.offset)
        } : {})
      }));
      allCount = (await db.icat_vars.count({
        where: {
          key: "press"
        }
      }));
      return {
        ok: true,
        data: data,
        allCount: allCount
      };
    } catch (error) {
      err = error;
      console.log(err);
      return {
        ok: false,
        msg: "服务器内部错误"
      };
    }
  }
};
